# -*- coding: utf-8 -*-
"""Sudoku.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ac5rEePW63tAYPzLSqG1iRfMImg5Xb3

**Row Validation**
"""

def notInRow(arr, row):

    st = set()

    for i in range(0, 9):

        if arr[row][i] in st:
            return False

        if arr[row][i] != '.':
            st.add(arr[row][i])
    
    return True

"""**Column Validation**"""

def notInCol(arr, col):

    st = set()

    for i in range(0, 9):      
        if arr[i][col] in st:
            return False

        if arr[i][col] != '.':
            st.add(arr[i][col])
    
    return True

"""**Box Validation**"""

def notInBox(arr, startRow, startCol):

    st = set()

    for row in range(0, 3):
        for col in range(0, 3):
            curr = arr[row + startRow][col + startCol]

            if curr in st:
                return False

            if curr != '.':
                st.add(curr)
            
    return True

"""**Valid Checker**"""

def isValid(arr, row, col):

    return (notInRow(arr, row) and notInCol(arr, col) and
            notInBox(arr, row - row % 3, col - col % 3))

def isValidConfig(arr, n):

    for i in range(0, n):
        for j in range(0, n):
            if not isValid(arr, i, j):
                return False
		
    return True

"""**Execution**"""

if __name__ == "__main__":

    board = [[ '6', '3', '.', '.', '7', '.', '.', '.', '.' ],
            [ '5', '.', '.', '1', '9', '6', '.', '.', '.' ],
            [ '.', '9', '8', '.', '.', '.', '.', '5', '.' ],
            [ '8', '.', '.', '.', '6', '.', '.', '.', '3' ],
            [ '4', '.', '.', '8', '.', '3', '.', '.', '1' ],
            [ '7', '.', '.', '.', '2', '.', '.', '.', '6' ],
            [ '.', '6', '.', '.', '.', '.', '2', '8', '.' ],
            [ '.', '.', '.', '4', '1', '9', '.', '.', '5' ],
            [ '.', '.', '.', '.', '8', '.', '.', '7', '9' ]]

    if isValidConfig(board, 9):
        print("YES")
    else:
        print("NO")